use_frameworks!

target 'NJMediator_NJTeachersHelerList_Example' do
  pod 'NJMediator_NJTeachersHelerList', :path => '../'

  target 'NJMediator_NJTeachersHelerList_Tests' do
    inherit! :search_paths

    
  end
end
